name: Call the reusable workflow defined in belt.yml and use its outputs

on:
  workflow_dispatch:

jobs:
  pre_test:
    uses: ./.github/workflows/belt.yml
    
  test:
    name: L1 handling matrix
    needs:
      - pre_test
    if: ${{ always() && needs.pre_test.result == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJson(inputs.SUPPORTED_ARCH) }}
        batch: ${{ fromJson(needs.pre_test.outputs.matrix_tests) }}
    uses: ./.github/workflows/batch.yml
    with:
      ARCH: ${{ matrix.arch }}
      TESTS: ${{ matrix.batch }}
  nested:
    name: Calling L2 workflow
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJson(inputs.SUPPORTED_ARCH) }}
    uses: ./.github/workflows/test.yml
    with:
      ARCH: ${{ matrix.arch }}
