name: Main

on:
  push:
    branches:
      - '**'


jobs:
  belt_conveyor:
    name: Belt
    uses: ./.github/workflows/belt.yml
    with:
#      SUPPORTED_ARCH: '["amd64","arm64"]'
      SUPPORTED_ARCH: '["amd64"]'
